version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: encontrapp_db
    environment:
      POSTGRES_USER: juan
      POSTGRES_PASSWORD: encontrapp123
      POSTGRES_DB: encontrapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U juan -d encontrapp"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
